tcp_h_dir = ..\..\TCPINC\
tcp_c_dir = ..\..\TCPLIB\
common_h_dir = ..\..\INCLUDE

memory_model = -ms
compile_options = -0 $(memory_model) -DCFG_H="XMASTREE.CFG" -oh -ok -os -s -oa -zp2 -zpw -we 
compile_options += -i=$(tcp_h_dir) -i=$(common_h_dir)


tcpobjs = packet.obj arp.obj eth.obj ip.obj utils.obj timer.obj ipasm.obj dns.obj udp.obj trace.obj
objs = xmastree.obj

all : clean xmastree.exe

clean : .symbolic
  @del xmastree.exe
  @del *.obj
  @del *.map

patch : .symbolic
  ..\..\utils\ptach xmastree.exe xmastree.map $(memory_model)

.asm : $(tcp_c_dir)

.cpp : $(tcp_c_dir)

.asm.obj :
  wasm -0 $(memory_model) $[*

.cpp.obj :
  wpp $[* $(compile_options)


xmastree.exe: $(tcpobjs) $(objs)
  wlink system dos option map option eliminate option stack=4096 name $@ file *.obj
